try:
	write(none)
catch err:
	write(err.message)
	write('hooops  error occurs')

func alert(name,times=8):
	times = '-' * times
	times.foreach => n:
		write(name)

alert('abbey',times=8)
alert('abbey')
try:
	alert('namme',k=5)
catch err:
	write(err.message)
n = ''
for i in ['h','e','l','l','o']:
	n = n + i
m,k = 'yes','true' ? 9==9 and 'p'  in n : 'no','false'
write(m+k)
write(n)

items = ['bag','pen','pecil']
write(items[0],items[1])
items[0] = 'bagss'
items.append('ruler')
items.append('passed')
write(items)

detail = {name:'username',password:'xxxxxx',mail:'mail@mail.co'}
write(detail.name == detail['name'])
write('name' in detail)
write('alll test passed')

